version: 0.0
os: linux
files:
  - source: build/libs/vote-counter-*.jar
    destination: /opt
permissions:
  - object: /opt
    pattern: "*.jar"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
  - ApplicationStop:
    - location: application-stop.sh
# - ApplicationStart:
#     - location: application-start.sh
