version: 0.0
os: linux
files:
  - source: /build/libs/vote-counter-1.0.0-SNAPSHOT.jar
    destination: /opt
hooks:
  - ApplicationStop:
    - location: application-stop.sh
  - ApplicationStart:
    - location: application-start.sh