version: 0.0
os: linux
files:
  - source: build/libs
    destination: /opt
hooks:
  ApplicationStop:
    - location: application-stop.sh
  ApplicationStart:
    - location: application-start.sh
      timeout: 15