version: 0.2

phases:
  build:
    commands:
      - gradle --version
      - gradle build
reports:
  jUnit_$CODEBUILD_SOURCE_VERSION:
    files:
      - '**/*'
    base-directory: 'build/test-results'
